name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and upload binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: brave-debloater-linux-x86_64
            binary_name: brave-debloater
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: brave-debloater-windows-x86_64.exe
            binary_name: brave-debloater.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: brave-debloater-macos-x86_64
            binary_name: brave-debloater
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: brave-debloater-macos-aarch64
            binary_name: brave-debloater

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Prepare binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} ${{ matrix.asset_name }}
        chmod +x ${{ matrix.asset_name }}

    - name: Prepare binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        copy target\${{ matrix.target }}\release\${{ matrix.binary_name }} ${{ matrix.asset_name }}

    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream

  package:
    name: Create release packages
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create source package
      run: |
        mkdir -p release-package
        cp config.json extensions.json README.md LICENSE release-package/
        tar -czf brave-debloater-source.tar.gz release-package/
        zip -r brave-debloater-source.zip release-package/

    - name: Upload source tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: brave-debloater-source.tar.gz
        asset_name: brave-debloater-source.tar.gz
        asset_content_type: application/gzip

    - name: Upload source zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: brave-debloater-source.zip
        asset_name: brave-debloater-source.zip
        asset_content_type: application/zip